@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMSwiZXhwIjoxNjgxNDA4ODkyfQ.rtgsfWmm_z-kEG3AQQTvF-4nnqbcprhTIenZaG2Uk9s

### Wines Index
GET http://localhost:3000/wines.json
Content-Type: application/json

### Wines Show
GET http://localhost:3000/wines/33.json
Content-Type: application/json

### Wines Update
PATCH http://localhost:3000/wines/33.json
Content-Type: application/json

{
  "name": "Floriana Gruner Veltliner"
}

### Wines Destroy
DELETE http://localhost:3000/wines/10

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "buckley",
  "email": "buckley@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users index
GET http://localhost:3000/users.json
Content-Type: application/json

### User show
GET http://localhost:3000/users/2.json
Content-Type: application/json

### User update
PATCH http://localhost:3000/users/1.json
Content-Type: application/json

{
  "username": "michael",
  "email": "michael@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### User destroy
DELETE http://localhost:3000/users/1

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "michael@test.com",
  "password": "password"
}

### Twilio Post
POST http://localhost:3000/sendtext.json
Content-Type: application/json

{
  "phone": "+17708261460",
  "textBody": "Hello!"
}