@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzE2MzcyOTF9.h2qvSGg0-eVwzGpZweeYfCP2BmIDyzGBPlt25xpTiv8

### Wines Index
GET http://localhost:3000/wines.json
Content-Type: application/json

### Wines Show
GET http://localhost:3000/wines/33.json
Content-Type: application/json

### Wines Update
PATCH http://localhost:3000/wines/33.json
Content-Type: application/json

{
  "name": "Ruggero di Bardo Susumaniello"
}

### Wines Destroy
DELETE http://localhost:3000/wines/10

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "Michael",
  "email": "michael@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users index
GET http://localhost:3000/users.json
Content-Type: application/json

### User show
GET http://localhost:3000/users/1.json
Content-Type: application/json

### User update
PATCH http://localhost:3000/users/1.json
Content-Type: application/json

{
  "username": "Michael",
  "email": "michael@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### User destroy


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "michael@test.com",
  "password": "password"
}

### Twilio Post
POST http://localhost:3000/sendtext.json
Content-Type: application/json

{
  "phone": "+17708261460",
  "textBody": "Hello!"
}

### User Profile Post
POST http://localhost:3000/user_profiles.json
Content-Type: application/json


{
  "user_id": "1"
}

###User Profile Show
GET http://localhost:3000/user_profiles/1.json
Content-Type: application/json

###User Profile Index
GET http://localhost:3000/user_profiles.json
Content-Type: application/json

### User Profile Destroy
DELETE http://localhost:3000/user_profiles/1
Content-Type: application/json




### User Profile Update
PATCH http://localhost:3000/user_profiles/1
Content-Type: application/json


{
  "name": "Michael",
  "bio": " ",
  "phone": " ",
  "location": " ",
  "user_img_url": " "

}